server.port=8080
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
capstone.member.password=${CAPSTONE_MEMBER_PASSWORD}
capstone.underwriter.password=${CAPSTONE_UNDERWRITER_PASSWORD}
